name : Demo pipeline 
on:
    push:
        branches:
            - main
            - dev 
    pull request:
        branches: [main,dev]
    schedule: 
        - cron: "*/1 * * * *"

jobs: 

    setup_job:
        runs_on: ubuntu-latest #macos-latest. windows-latest
        steps:
            - name: create file 
              run: touch github-action.txt
            - name: print hello world 
              run: echo Hello world 
            - name: display readme file 
              run: cat README.md 
    build_job: 
        runs-on: windows-latest
        steps:
            - name: displat hello
              run: echo hello
    deploy_job:
        runs-on: macos-latest 
        steps:
            - run: echo hello mac
